# Generated by Django 2.1.3 on 2018-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=150)),
            ],
        ),
    ]
