# Generated by Django 2.1.3 on 2018-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0002_remove_post_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
