# Generated by Django 2.1.3 on 2018-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0003_post_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=150)),
                ('data_nasc', models.CharField(max_length=150)),
                ('data_hist', models.DateField()),
                ('rg', models.CharField(max_length=14)),
                ('tel', models.CharField(max_length=10)),
                ('cel', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=150)),
                ('endereco_n', models.CharField(max_length=8)),
                ('endereco_cep', models.CharField(max_length=15)),
                ('endereco_cid', models.CharField(max_length=100)),
                ('endereco_est', models.CharField(max_length=50)),
                ('curso_opc1', models.CharField(max_length=150)),
                ('period_opc1', models.CharField(max_length=2)),
                ('curso_opc2', models.CharField(max_length=150)),
                ('period_opc2', models.CharField(max_length=2)),
                ('opc_info', models.BooleanField(default=False)),
            ],
        ),
    ]
