# Generated by Django 2.1.3 on 2018-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0004_candidatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='email',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatos',
            name='email_opc',
            field=models.CharField(choices=[('1', 'gmail.com'), ('2', 'hotmail.com'), ('3', 'outlook.coom'), ('4', 'ig.com'), ('5', 'yahool.com.br')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='curso',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='curso_opc1',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='curso_opc2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='period_opc1',
            field=models.CharField(choices=[('1', 'Matutino'), ('2', 'Noturno')], max_length=2),
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='period_opc2',
            field=models.CharField(choices=[('1', 'Matutino'), ('2', 'Noturno')], max_length=2),
        ),
    ]
