# Generated by Django 2.1.3 on 2018-12-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0005_auto_20181204_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.CharField(max_length=10)),
                ('nome_curso', models.CharField(max_length=150)),
            ],
        ),
    ]
