# Generated by Django 2.1.3 on 2019-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0006_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150)),
                ('periodo', models.CharField(max_length=150)),
                ('disciplina', models.CharField(max_length=150)),
                ('sala', models.CharField(max_length=150)),
                ('dia', models.CharField(max_length=150)),
                ('serie', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=150)),
            ],
        ),
    ]
