# Generated by Django 2.1.3 on 2019-02-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blo', '0007_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unidades', models.CharField(blank=True, choices=[('01', 'VG'), ('02', 'CS'), ('03', 'UNOPAR')], max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='horario',
            name='periodo',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sala',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='serie',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='horario',
            name='id_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blo.Courses'),
            preserve_default=False,
        ),
    ]
