# Generated by Django 2.1.3 on 2019-02-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0008_auto_20190218_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='email',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='unidades',
        ),
    ]
